name: Go Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Go Test And Build
    runs-on: ubuntu-latest
    steps:

      - name: load Go 1.22.4 env
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.4
        id: go

      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: |
          go test -v ./...
